




CREATE TABLE member 
(	ID VARCHAR2(15) NOT NULL ENABLE, 
	PW VARCHAR2(15) NOT NULL ENABLE, 
	NAME VARCHAR2(10) NOT NULL ENABLE, 
	BIRTHDAY VARCHAR2(11) NOT NULL ENABLE, 
	TEL VARCHAR2(15) NOT NULL ENABLE, 
	ADDR VARCHAR2(40) NOT NULL ENABLE, 
	EMAIL VARCHAR2(40) NOT NULL ENABLE
);